name: Laravel

on: [ pull_request ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      pgsql:
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: laravel
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies 
      run: composer install -q --working-dir=webApp --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env
      run: php -r "file_exists('webApp/.env') || copy('webApp/.env.example', 'webApp/.env');"

    - name: Generate key
      run: php webApp/artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 webApp/storage webApp/bootstrap/cache

    - name: Install front-end dependencies
      run: |
        cd webApp
        npm install
        npm run build

    - name: Update database
      env:
        DB_PASSWORD: postgres
      run: php webApp/artisan migrate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: webApp/vendor/bin/phpunit webApp/tests
      env:
        DB_PASSWORD: postgres
        LOG_CHANNEL: stderr
